# Generated by Django 4.2.4 on 2023-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAPP', '0003_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
